FROM ubuntu:trusty
MAINTAINER Alan Franzoni <username@franzoni.eu>
RUN apt-get update ; apt-get -y install language-pack-en
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8 

